apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-data-protection-by-preset-label
  annotations:
    policies.kyverno.io/title: Enforce By Preset Label
    policies.kyverno.io/category: K10
    policies.kyverno.io/subject: Deployment, StatefulSet
    policies.kyverno.io/description: >-
      Ensure all namespaces include a label referencing a valid K10 SLA (Policy Preset) for data protection.
      This policy can be used in combination with generate ClusterPolicy to generate to automatically create a K10 policy based on the specified SLA.
      
      NOTE: This example assumes that K10 policy presets named "gold", "silver", and "bronze" have been pre-created and K10 was deployed into the `kasten-io` namespace.
spec:
  validationFailureAction: Enforce
  validationFailureActionOverrides:
    - action: Audit
      namespaces:
        - argocd
        - kasten-io
        - kasten-io-mc
  rules:
  - name: enforce-data-protection-by-preset-label
    match:
      resources:
        kinds:
        - Namespace
    validate:
      message: >-
        Namespaces must specify a "dataprotection" label with a value corresponding to a Kasten K10 SLA:
        
          "gold" - Hourly backups exported to object storage
          "silver" - Daily backups exported to object storage
          "bronze" - Daily local snapshots
          "none" - Living on the edge!
          
      pattern:
        metadata:
          labels:
            dataprotection: gold|silver|bronze|none