apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    dataprotection: bronze
spec:
  selector:
    matchLabels:
      app: vet-app
      component: mysql
  serviceName: mysql-service
  replicas: 1
  template:
    metadata:
      labels:
        app: vet-app
        component: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: mysql-secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi