apiVersion: v1
kind: Service
metadata:  
  labels:
    app: vet-app
    component: mysql
  name: mysql-service
spec:
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: vet-app
    component: mysql
  type: ClusterIP